<%@ Page Title="Category" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Category.aspx.cs" Inherits="AppDev_GW.Category" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="col-md-7">
    <div class="card">
         <asp:TextBox ID="txtId" runat="server" Visible="false"></asp:TextBox>
        <div>
            <asp:RequiredFieldValidator ID="rfvName" runat="server" ControlToValidate="txtName"   
            ErrorMessage="Please enter a category name" ForeColor="Red"></asp:RequiredFieldValidator>  
        </div>
         
        <div class="form-input pl-3">
            <asp:Label ID="lbTitle" runat="server" Text="Categories: " Font-Size="Large"></asp:Label>
            <asp:TextBox ID="txtName" runat="server"></asp:TextBox>
            <asp:Button ID="btnAdd" runat="server" Text="Insert" onClick="btnAddItem_Click" CssClass="btn btn-info btn-lg"/>
            <asp:Button ID="btnClear" runat="server" Text="Clear" onClick="btnClear_Click" CssClass="btn btn-danger btn-lg"/>
        </div>
        <br />
        <div class="card table table-hover">
            <asp:GridView ID="GridView1" orderStyle="None" GridLines="None"  runat="server" DataKeyNames="ID" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" 
            OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added."
            AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" CssClass="table table-striped">   
            </asp:GridView>
        </div>

    </div>
        </div>
</asp:Content>
