<%@ Page Title="Category" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Category.aspx.cs" Inherits="AppDev_GW.Category" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Label ID="lbTitle" runat="server" Text="Product Category" Font-Size="Larger"></asp:Label>

    <div>
        <asp:Button ID="btnAdd" runat="server" Text="Add" />
        <asp:Button ID="btnUpdate" runat="server" Text="Update" />
    </div>

    <div>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"></asp:GridView>
    </div>
</asp:Content>
