<%@ Page Title="Customer" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Customer.aspx.cs" Inherits="AppDev_GW.Customer" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <div style="font-size:x-large">Customers</div>
        <div>
            <table>
                <tr>
                    <td>
                         <asp:TextBox ID="txtId" runat="server" Visible="false"></asp:TextBox>
                    </td>
                </tr>
                 <tr>
                    <td>
                        Customer Name :
                    </td>
                     <td>
                          <asp:TextBox ID="txtName" runat="server"></asp:TextBox>
                     </td>
                </tr>
                 <tr>
                    <td>
                        Customer Phone : 
                    </td>
                     <td>
                         <asp:TextBox ID="txtNumber" runat="server"></asp:TextBox>
                     </td>
                </tr>
                 <tr>
                    <td>
                        Customer Address :
                    </td>
                     <td>
                          <asp:TextBox ID="txtAddress" runat="server"></asp:TextBox>
                     </td>
                </tr>
                 <tr>
                    <td>
                        Customer Email : 
                    </td>
                     <td>
                         <asp:TextBox ID="txtEmail" runat="server"></asp:TextBox>
                     </td>
                </tr>
                 <tr>
                    <td>
                        Customer Type : 
                    </td>
                     <td>
                         <asp:DropDownList ID="ddlType" runat="server">
                             <asp:ListItem>Black</asp:ListItem>
                             <asp:ListItem>Gold</asp:ListItem>
                             <asp:ListItem>Platinum</asp:ListItem>
                         </asp:DropDownList>                        
                        </td>
                </tr>
          
                <tr>
                    <td>&nbsp;</td>
                    <td>
                        <asp:Button ID="btnAdd" runat="server" Text="Insert" OnClick="btnAddItem_Click"/>
                        <asp:Button ID="btnClear" runat="server" Text="Clear"  OnClick="btnClear_Click"/>
                    </td>
                    
                </tr>
            </table>
        </div>
        <div>
        <asp:GridView ID="GridView1" runat="server" DataKeyNames="ID" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" 
        OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added."
        AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" CssClass="table table-striped">   
        </asp:GridView>
    </div>
</asp:Content>
