<%@ Page Title="User" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="User.aspx.cs" Inherits="AppDev_GW.Contact" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
            <div style="font-size:x-large">Users</div>
        <div>
            <table>
                <tr>
                    <td>
                         <asp:TextBox ID="txtId" runat="server" Visible="false"></asp:TextBox>
                    </td>
                </tr>
                 <tr>
                    <td>
                        User Name :
                    </td>
                     <td>
                          <asp:TextBox ID="txtName" runat="server"></asp:TextBox>
                                              <asp:RequiredFieldValidator ID="rfvQuantity" runat="server" ControlToValidate="txtName"   
                     ErrorMessage="Please enter username" ForeColor="Red"></asp:RequiredFieldValidator> 

                     </td>
                </tr>
                 <tr>
                    <td>
                        User Password : 
                    </td>
                     <td>
                         <asp:TextBox ID="txtPassword" runat="server"></asp:TextBox>
                                              <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtPassword"   
                     ErrorMessage="Please enter password" ForeColor="Red"></asp:RequiredFieldValidator> 

                     </td>
                </tr>
                 <tr>
                    <td>
                        User Type :
                    </td>
                     <td>
                         <asp:DropDownList ID="ddlType" runat="server">
                             <asp:ListItem>Admin</asp:ListItem>
                             <asp:ListItem>General</asp:ListItem>
                         </asp:DropDownList>                        
                        </td>
                </tr>
          
                <tr>
                    <td>&nbsp;</td>
                    <td>
                        <asp:Button ID="btnAdd" runat="server" Text="Insert" OnClick="btnAddItem_Click"/>
                        <asp:Button ID="btnClear" runat="server" Text="Clear"  OnClick="btnClear_Click"/>
                    </td>
                    
                </tr>
            </table>
        </div>
        <div>
        <asp:GridView ID="GridView1" runat="server" DataKeyNames="ID" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" 
        OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added."
        AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" CssClass="table table-striped">   
        </asp:GridView>
    </div>
</asp:Content>
