<%@ Page Title="User" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="User.aspx.cs" Inherits="AppDev_GW.Contact" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
            <asp:Label ID="lbTitle" runat="server" Font-Size="XX-Large" Text="Users"></asp:Label>

            <br />

            <div class="form-group">
            <table>
                <tr>
                    <td>
                        <asp:Label ID="lbName" runat="server" Text="User Name"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtName" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lbPassword" runat="server" Text="Password"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtPassword" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lbType" runat="server" Text="Type of User"></asp:Label>
                    </td>
                    <td>
                        <asp:DropDownList ID="ddlType" runat="server">
                            <asp:ListItem>Admin</asp:ListItem>
                            <asp:ListItem>General</asp:ListItem>
                        </asp:DropDownList>
                    </td>
                </tr>
                <tr>
                    <td>
                        &nbsp;</td>
                    <td>
                        <asp:Button class="btn btn-success" ID="btnSave" runat="server" Text="Save" OnClick="btnSave_Click" />
                        <asp:Button class="btn btn-primary" ID="btnClear" runat="server" Text="Clear" OnClick="btnClear_Click" />
                    </td>
                </tr>
            </table>
            </div>

            <hr />

            <div>
                <asp:GridView ID="GridView1" runat="server" DataKeyNames="Id" OnRowDataBound="OnRowDataBound" OnSelectedIndexChanged="GridView1_SelectedIndexChanged"
                OnRowDeleting="OnRowDeleting" rowCommand="RowSelected" EmptyDataText="No records has been added."
                AutoGenerateDeleteButton="true" CssClass="table table-striped">
                </asp:GridView>
            </div>
        </div>

</asp:Content>
